### ISSUE TITLE
Endless Access violations

### ISSUE THREAD

**Issue by AnthonyIV** [vhanla/winxcorners#2]
I get an endless stream of these error messages when I start the new 1.2 beta version, launching it as administrator makes no difference. The error messages only stop coming when I kill the application. The older version works.

<img width="1007" alt="WinXCorners Error Message" src="https://user-images.githubusercontent.com/30813107/59972181-81858400-953f-11e9-90a6-0bc2f24f5d13.PNG">

The windows install is a fairly recent one, maybe a month or two old now, I'm on Windows 10 Home v1803. It's a bootcamp partion on a Macbook Pro. One other thing that does particularly set my system apart and may be a cause is that I run an eGPU to drive my monitor, when in Windows this is my only monitor, internal Laptop monitor is blank. Other than that the install is fairly fresh and has little that I can think of that would be conflicting with the software.

Happy to test or provide further information as needed.

**Comment by mjherich** [comment]
I'm getting the same issue. The stable version works like a charm besides the missing multi-monitor support.

**Comment by vhanla** [comment]
Thank you for your feedback, I'm attaching an updated executable fixing an error that shows Access Violation (commit 062e18de84fcce85e69b42dbe23ac03efd4cce33), hotpost timer was trying to read a window for OSD visualization that was not created yet. That might be the error.

The new executable includes an error reporting tool (MadExcept) that will allow to generate a bugreport.txt file in order to send here if error persists.

[WinXCornersWithErrorRerporting.zip](https://github.com/vhanla/winxcorners/files/3332161/WinXCornersWithErrorRerporting.zip)

Please try this new version, and if error persists, save the error report to a txt file and upload here.

**Comment by mjherich** [comment]
Getting `exception message  : Failed to get data for 'SystemUsesLightTheme'.`
[bugreport.txt](https://github.com/vhanla/winxcorners/files/3332257/bugreport.txt)
[bugreportadmin.txt](https://github.com/vhanla/winxcorners/files/3332258/bugreportadmin.txt)

**Comment by vhanla** [comment]
My bad, that was an error accessing registry entries only available on Windows 10 May 2019 Update. Thank you, I attached new executable fixing that error.

[WinXCornersRegistryFix.zip](https://github.com/vhanla/winxcorners/files/3332344/WinXCornersRegistryFix.zip)

**Comment by mjherich** [comment]
You are the man! Feels just like my macbook now 😄

**Comment by AnthonyIV** [comment]
Confirmed now working without issue, very nice!

**Comment by strakerc** [comment]
I am still seeing this problem with the executable downloaded directly from the github page. Did you update the main file?
